In [7]:
import numpy as np

# (a) Reverse the NumPy array
arr = np.array([1, 2, 3, 6, 4, 5])
arr_reversed = arr[::-1]
print("Reversed array:", arr_reversed)

# (b) Flatten array using two methods
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flat1 = array1.flatten()
flat2 = array1.ravel()
print("Flattened with flatten():", flat1)
print("Flattened with ravel():", flat2)

# (c) Compare two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
are_equal = np.array_equal(arr1, arr2)
print("Arrays equal:", are_equal)

# (d) Most frequent value and their indices
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
vals_x, counts_x = np.unique(x, return_counts=True)
max_count_x = np.max(counts_x)
most_freq_vals_x = vals_x[counts_x == max_count_x]
indices_x = np.where(np.isin(x, most_freq_vals_x))[0]
print("Most frequent in x:", most_freq_vals_x)
print("Indices in x:", indices_x)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
vals_y, counts_y = np.unique(y, return_counts=True)
max_count_y = np.max(counts_y)
most_freq_vals_y = vals_y[counts_y == max_count_y]
indices_y = np.where(np.isin(y, most_freq_vals_y))[0]
print("Most frequent in y:", most_freq_vals_y)
print("Indices in y:", indices_y)

# (e) Sum of elements in matrix gfg
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum_all = np.sum(gfg)
sum_row = np.sum(gfg, axis=1)
sum_col = np.sum(gfg, axis=0)
print("Sum of all elements:", sum_all)
print("Row-wise sum:\n", sum_row)
print("Column-wise sum:\n", sum_col)

# (f) Matrix n_array calculations
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
sum_diag = np.trace(n_array)
eig_vals, eig_vecs = np.linalg.eig(n_array)
inverse_matrix = np.linalg.inv(n_array)
determinant = np.linalg.det(n_array)
print(" Sum of diagonal elements:", sum_diag)
print(" Eigenvalues:\n", eig_vals)
print(" Eigenvectors:\n", eig_vecs)
print(" Inverse matrix:\n", inverse_matrix)
print(" Determinant:", determinant)

# (g) Matrix multiplication and covariance
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
mult1 = np.matmul(p1, q1)
cov1 = np.cov(p1.flatten(), q1.flatten())
print("Multiplication result:\n", mult1)
print("Covariance matrix:\n", cov1)

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
mult2 = np.matmul(p2, q2)
cov2 = np.cov(p2.flatten(), q2.flatten())
print("Multiplication result:\n", mult2)
print("Covariance matrix:\n", cov2)

# (h) Inner, outer and cartesian products
x_h = np.array([[2, 3, 4], [3, 2, 9]])
y_h = np.array([[1, 5, 0], [5, 10, 3]])
inner_prod = np.inner(x_h, y_h)
outer_prod = np.outer(x_h.flatten(), y_h.flatten())

from itertools import product
cartesian_prod = list(product(x_h.flatten(), y_h.flatten()))
print("Inner product:\n", inner_prod)
print("Outer product:\n", outer_prod)
print("Cartesian product (first 10 pairs):", cartesian_prod[:10])




Reversed array: [5 4 6 3 2 1]
Flattened with flatten(): [1 2 3 2 4 5 1 2 3]
Flattened with ravel(): [1 2 3 2 4 5 1 2 3]
Arrays equal: True
Most frequent in x: [1]
Indices in x: [0 5 7 8 9]
Most frequent in y: [1 3]
Indices in y: [0 1 2 4 8 9]
Sum of all elements: 45
Row-wise sum:
 [[14]
 [16]
 [15]]
Column-wise sum:
 [[20  9 16]]
 Sum of diagonal elements: 176
 Eigenvalues:
 [98.16835147 28.097044   49.73460452]
 Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
 Inverse matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
 Determinant: 137180.0000000001
Multiplication result:
 [[16 19]
 [26 31]]
Covariance matrix:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Multiplication result:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]
Inner product:
 [[17 52]
 [13 62]]
O

In [8]:
# Q2 Answers

array = np.array([[1, -2, 3], [-4, 5, -6]])
print("Element-wise absolute value:\n", np.abs(array))

print("Percentiles (flattened):",
      np.percentile(array, 25),
      np.percentile(array, 50),
      np.percentile(array, 75))

print("Percentiles by column:")
print("25th:", np.percentile(array, 25, axis=0))
print("50th:", np.percentile(array, 50, axis=0))
print("75th:", np.percentile(array, 75, axis=0))

print("Percentiles by row:")
print("25th:", np.percentile(array, 25, axis=1))
print("50th:", np.percentile(array, 50, axis=1))
print("75th:", np.percentile(array, 75, axis=1))

print("Mean, Median, Std deviation (flattened):",
      np.mean(array), np.median(array), np.std(array))

print("Mean by column:", np.mean(array, axis=0))
print("Median by column:", np.median(array, axis=0))
print("Std deviation by column:", np.std(array, axis=0))

print("Mean by row:", np.mean(array, axis=1))
print("Median by row:", np.median(array, axis=1))
print("Std deviation by row:", np.std(array, axis=1))

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor values:", np.floor(a))
print("Ceiling values:", np.ceil(a))
print("Truncated values:", np.trunc(a))
print("Rounded values:", np.round(a))



Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]
Percentiles (flattened): -3.5 -0.5 2.5
Percentiles by column:
25th: [-2.75 -0.25 -3.75]
50th: [-1.5  1.5 -1.5]
75th: [-0.25  3.25  0.75]
Percentiles by row:
25th: [-0.5 -5. ]
50th: [ 1. -4.]
75th: [2.  0.5]
Mean, Median, Std deviation (flattened): -0.5 -0.5 3.8622100754188224
Mean by column: [-1.5  1.5 -1.5]
Median by column: [-1.5  1.5 -1.5]
Std deviation by column: [2.5 3.5 4.5]
Mean by row: [ 0.66666667 -1.66666667]
Median by row: [ 1. -4.]
Std deviation by row: [2.05480467 4.78423336]
Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


In [9]:
# Q3 Answers

array3a = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted array:", np.sort(array3a))
print("Indices of sorted array:", np.argsort(array3a))
print("4 smallest elements:", np.partition(array3a, 3)[:4])
print("5 largest elements:", np.partition(array3a, -5)[-5:])

array3b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("Integer elements only:", array3b[array3b == array3b.astype(int)])
print("Float elements only:", array3b[array3b != array3b.astype(int)])



Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]
Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


In [18]:
# Q4 Functions

from google.colab import files
uploaded = files.upload()
import numpy as np


def img_to_array(path):
    img = Image.open(path)
    img_np = np.array(img)

    if len(img_np.shape) == 2:  # Grayscale
        np.savetxt('grayscale_image.txt', img_np, fmt='%d')
        print("Grayscale image saved as grayscale_image.txt")
    elif len(img_np.shape) == 3:  # RGB
        np.savetxt('red_channel.txt', img_np[:,:,0], fmt='%d')
        np.savetxt('green_channel.txt', img_np[:,:,1], fmt='%d')
        np.savetxt('blue_channel.txt', img_np[:,:,2], fmt='%d')
        print("RGB image saved as red_channel.txt, green_channel.txt, blue_channel.txt")
    else:
        raise ValueError("Unsupported image format")
    return img_np

def load_saved_file(file_path):
    loaded_array = np.loadtxt(file_path)
    print(f"Loaded data from {file_path}:\n", loaded_array)
    return loaded_array

img_array = img_to_array('wp9200875.jpg')
red_data = load_saved_file('red_channel.txt')

Saving wp9200875.jpg to wp9200875 (2).jpg
RGB image saved as red_channel.txt, green_channel.txt, blue_channel.txt
Loaded data from red_channel.txt:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
